---

apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: webhook
spec:
  service:
    ports:
      - port: 12000
        targetPort: 12000
  webhook:
    slack-notification:
      port: "12000"
      endpoint: "/slack-notification"
      method: POST
      url: webhook.34.91.15.148.nip.io

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webhook
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
           name: webhook-eventsource-svc
           port:
             number: 12000
    host: webhook.104.196.111.81.xip.io